// <auto-generated />
namespace LLIB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class bookandcustomerandorderandusercreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookandcustomerandorderandusercreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202002131546368_bookandcustomerandorderandusercreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
